
build:
    ./gradlew build

repl:
    ./gradlew :app:run --quiet --console=plain

script script_file:
    ./gradlew :app:run --args="{{invocation_directory()}}/{{script_file}}" --quiet --console=plain

all-scripts:
    echo "\nCOUNTER"
    just script scripts/counter.lox
    echo "\nENVIRONMENTS"
    just script scripts/environments.lox
    echo "\nFIB"
    just script scripts/fib.lox
    echo "\nLOOPS"
    just script scripts/loops.lox
    echo "\nPRINT_THINGS"
    just script scripts/print_things.lox
    echo "\nSAYHI"
    just script scripts/sayhi.lox
    echo "\nSCOPING"
    just script scripts/scoping.lox
    echo "\nVARIABLES"
    just script scripts/variables.lox

gen-ast: 
    ./gradlew :tools:run --args="{{invocation_directory()}}/app/src/main/kotlin/com/ericrochester/klox" --quiet --console=plain
