/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("klox.kotlin-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    // implementation(project(":tools"))
    implementation("io.github.microutils:kotlin-logging-jvm:3.0.5")
    implementation("org.slf4j:slf4j-simple:2.0.13")
}

application {
    // Define the main class for the application.
    mainClass.set("com.ericrochester.klox.app.AppKt")
}