/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("klox.kotlin-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    // implementation(project(":tools"))
}

application {
    // Define the main class for the application.
    mainClass.set("com.ericrochester.klox.app.AppKt")
}